### ISSUE TITLE
"Link Data to simulations" in chart editor - apply same color to all data/simulation results

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2120]
When "Link data to simulations" checkbox is checked, observed data that are mapped to a simulation output are automaticall added to the plot when adding a simulation result, which is very handy

![image](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25903040/19cdc4e6-de8c-4d18-8db7-46f7b96068f2)

It would be even better if the were plotted with the same color as the added simulation result.

**Comment by rwmcintosh** [comment]
@PavelBal should this color sync be retained if someone changes the color of a result or observation in the chart editor?

So, 
1.  User clicks 'Link Data to Simulations'
2. Observations are added and colors are corrected
3. User changes the color of one of the curves that are connected

Should all the curves related be updated? Should that be a separate option?

**Comment by PavelBal** [comment]
No, only when the results/data are added.

**Comment by PavelBal** [comment]
This is still buggy af but let's move it to 12.3. Also create another issue: https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2720

**Comment by Yuri05** [comment]
@PavelBal Seems to be the same issue as the 2nd part of https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2720 (which I just reopened because it's not working)?

**Comment by PavelBal** [comment]
Lets move to v13 please
