### ISSUE TITLE
Data Importer imports extended properties without name

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/OSPSuite.Core#2417]
Investigating https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2231

And @Yuri05 makes the suggestion to check for nulls in these lines

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/0d01657eb8defd5501d25ffbcf21c26fa1869a06/src/OSPSuite.Infrastructure.Import/Core/Mappers/DataSetToDataRepositoryMapper.cs#L39-L44

But what I found was that both name and value are null for these properties (the fix has introduced a placehoder name):

![Image](https://github.com/user-attachments/assets/1f2ce724-d001-4df0-9580-86b6043caf63)

The fact that the extended property is somehow in the cache during serialization means that during this phase, the name and value both have non-null values and must be renamed after.

I would start investigating what happens with the created `ExtendedProperty` after it's added to the cache.

**Comment by Yuri05** [comment]
@rwmcintosh I think this is fixed in the meanwhile?

**Comment by rwmcintosh** [comment]
I don't think so. We mitigated it such that the project can still be opened if a null or empty extended property is serialized into the project somehow, but we still don't know how it gets that way.
